# Generated by Django 2.2.1 on 2019-05-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dip_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='send_email',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='send_telegram',
            field=models.BooleanField(null=True),
        ),
    ]
