# Generated by Django 2.2.1 on 2019-05-31 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dip_manager', '0002_auto_20190530_2329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='сreator',
            new_name='author',
        ),
    ]
