# Generated by Django 2.2.1 on 2019-06-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dip_manager', '0004_auto_20190601_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='date_post',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_post',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_update',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='date_post',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_start',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_update',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
